DROP DATABASE IF EXISTS fyre_db;
CREATE DATABASE fyre_db;

CREATE TABLE fyreList 
(
id INT AUTO_INCREMENT NOT NULL,
Title VARCHAR(50) NOT NULL,
Artist VARCHAR(50) NOT NULL,
Genre VARCHAR(50) NOT NULL,
PRIMARY KEY (id) 
);